# --- Basic options --- #

# Name of website
title: "SAMUEL J MATHEW"

# Short description of your site
description: A virtual proof that I'm awesome

author: Samuel J Mathew

favicon: https://www.gravatar.com/avatar/09dc3e52326e20237833d148be899750?s=16&d=favicon&r=PG

